# Generated by Django 3.1.1 on 2021-01-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleinfo',
            old_name='max_age',
            new_name='max_exp',
        ),
        migrations.RenameField(
            model_name='articleinfo',
            old_name='min_age',
            new_name='min_exp',
        ),
    ]
