# Generated by Django 3.1.1 on 2021-01-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210116_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleinfo',
            name='max_exp',
        ),
        migrations.RemoveField(
            model_name='articleinfo',
            name='min_exp',
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='batch',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='experiance',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='exam_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='interview_date',
            field=models.CharField(max_length=200),
        ),
    ]
