# Generated by Django 3.1.1 on 2021-01-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210117_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='batch',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='experiance',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
