# Generated by Django 3.1.1 on 2021-01-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210117_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='batch',
            field=models.CharField(max_length=300),
        ),
    ]
