# Generated by Django 3.1.1 on 2021-01-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210117_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='batch',
            field=models.CharField(default='2021', max_length=300),
        ),
    ]
