# Generated by Django 3.1.1 on 2021-01-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210117_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleinfo',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='articleinfo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='articleinfo',
            name='eligibility1',
        ),
        migrations.RemoveField(
            model_name='articleinfo',
            name='eligibility2',
        ),
        migrations.RemoveField(
            model_name='articleinfo',
            name='eligibility3',
        ),
        migrations.RemoveField(
            model_name='articleinfo',
            name='eligibility4',
        ),
        migrations.RemoveField(
            model_name='articleinfo',
            name='eligibility5',
        ),
        migrations.RemoveField(
            model_name='articleinfo',
            name='experiance',
        ),
        migrations.RemoveField(
            model_name='articleinfo',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='about_company',
            field=models.CharField(default='No info', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='company_name',
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='eligibility',
            field=models.CharField(default=None, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='job_description',
            field=models.CharField(default=None, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='location',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='max_age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='min_age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
