# Generated by Django 3.1.1 on 2021-01-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articleinfo_selection_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=500)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_update', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=400)),
                ('post_name', models.CharField(max_length=200)),
                ('begin_date', models.DateField()),
                ('last_date', models.DateField()),
                ('exam_date', models.CharField(max_length=200)),
                ('interview_date', models.CharField(max_length=200)),
                ('selection_procedure', models.CharField(default='', max_length=5000)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('location', models.CharField(max_length=500)),
                ('total_post', models.IntegerField()),
                ('eligibility', models.CharField(max_length=5000)),
                ('job_description', models.CharField(max_length=5000)),
                ('about_company', models.CharField(max_length=5000)),
                ('apply_link', models.URLField()),
                ('offical_link', models.URLField()),
                ('admitcard_avail', models.CharField(blank=True, default='Notified Soon', max_length=300)),
                ('admitcard_link', models.URLField(blank=True, default='')),
                ('result_dec', models.CharField(blank=True, default='Notified Soon', max_length=300)),
                ('result_link', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleInfo',
        ),
    ]
