# Generated by Django 3.1.1 on 2021-01-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20210121_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlejob',
            old_name='admitcard_avail',
            new_name='admitcard_date',
        ),
        migrations.RenameField(
            model_name='articlejob',
            old_name='result_dec',
            new_name='result_date',
        ),
    ]
