# Generated by Django 3.1.1 on 2021-01-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20210121_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlejob',
            name='admitcard_date',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='articlejob',
            name='exam_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='articlejob',
            name='interview_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='articlejob',
            name='result_date',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='articlejob',
            name='selection_procedure',
            field=models.CharField(help_text='Separate with comma', max_length=5000),
        ),
    ]
