# Generated by Django 3.1.1 on 2021-01-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20210121_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlejob',
            name='syllabus_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='articlejob',
            name='admitcard_date',
            field=models.CharField(blank=True, help_text='If not then enter Notified Soon', max_length=300),
        ),
        migrations.AlterField(
            model_name='articlejob',
            name='exam_date',
            field=models.CharField(blank=True, help_text='If not then enter Notified Soon', max_length=200),
        ),
    ]
